### ISSUE TITLE
Ban/Kick Embed ändert sich nicht immer

### ISSUE THREAD

**Issue by Fedox-die-Ente** [nevar-bot/nevar#18]
![image](https://github.com/nevar-bot/nevar/assets/67076970/8b666ef7-1b54-43d3-9277-46fe4d161c66)

Embed Updated sich nicht immer nach bestätigen

**Comment by 1887jonas** [comment]
Ist es ersichtlich wann das auftritt?

**Comment by Fedox-die-Ente** [comment]
Nein, einfach so random irgendwann
